version: "3"
services:
  sv:
    image: tensorflow/serving:latest
    ports:
      - 8500:8500
      - 8501:8501
    volumes:
      - ./serving_dir/tip_model:/models/tip_model
    environment:
      MODEL_NAME: tip_model

                